name: Audit

on:
  push:
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: "0 0 * * *"

jobs:
  audit:
    needs: [cargo-deny] # security-audit,
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: exit 0
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0
          override: true
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  cargo-deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans
          - licenses
          - sources
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          rust-version: "1.60.0"
          command: check ${{ matrix.checks }} -s
          arguments: --all-features
          log-level: warn